import org.junit.Before;
import org.junit.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.URL;
import java.util.ArrayList;

/**
 * Created by katana on 3/27/17.
 */
public class GIFGeneratorTest {

    private GIFGenerator generator;

    @Before
    public void setUp() {

        generator = new GIFGenerator();

    }

    /* The file generated by this test must be checked manually to make sure the gif cycles properly. */
    @Test
    public void generate() throws IOException {

        //Make the test images array
        ArrayList<BufferedImage> images = new ArrayList<BufferedImage>();

        URL pic1Url = new URL("http://www.clipartbest.com/cliparts/KTn/XXK/KTnXXK8Ec.png");
        URL pic2Url = new URL("http://www.iconsdb.com/icons/preview/orange/fish-xxl.png");

        BufferedImage pic1Img = ImageIO.read(pic1Url);
        BufferedImage pic2Img = ImageIO.read(pic2Url);

        images.add(pic2Img);
        images.add(pic1Img);

        //Generate the gif
        ByteArrayOutputStream gifStream = generator.generate(2, images);

        //Output the gif to the file system for viewing (it will be output through the response in our actual implementation)
        OutputStream outputStream = new FileOutputStream("src/test/resources/test.gif");
        gifStream.writeTo(outputStream);

    }

}